// ==========================================
// DATA BUNPOU (KALIMAT) LENGKAP 40 BAB
// ==========================================
const bunpouData = [
    { id: 1, title: "01 ANGKA", items: [
        { j: "私の電話【番号】は【ゼロ】、【九】、【ゼロ】、【一】、【二】、【三】です。", r: "Watashi no denwa bangou wa zero, kyuu, zero, ichi, ni, san desu.", m: "Nomor telepon saya 0-9-0-1-2-3." },
        { j: "【一】、【二】、【三】、【四】、【五】。みんなで数えましょう。", r: "Ichi, ni, san, yon, go. Minna de kazoemashou.", m: "Satu, dua, tiga, empat, lima. Mari kita hitung bersama." },
        { j: "【六】時に起きて、【七】時に朝ご飯を食べて、【八】時に家を出ます。", r: "Roku ji ni okite, shichi ji ni asagohan wo tabete, hachi ji ni ie wo demasu.", m: "Saya bangun jam enam, sarapan jam tujuh, dan keluar rumah jam delapan." },
        { j: "【九】時から【十】時まで日本語の授業があります。", r: "Ku ji kara juu ji made nihongo no jugyou ga arimasu.", m: "Ada pelajaran bahasa Jepang dari jam sembilan sampai jam sepuluh." },
        { j: "このノートは【百】円、あのペンは【千】円、あのかばんは【一万】円です。", r: "Kono nooto wa hyaku en, ano pen wa sen en, ano kaban wa ichiman en desu.", m: "Buku ini 100 yen, pulpen itu 1.000 yen, dan tas itu 10.000 yen." },
        { j: "この車は【十万】円ではなく、【百万】円です。", r: "Kono kuruma wa juuman en dewa naku, hyakuman en desu.", m: "Mobil ini bukan 100 ribu yen, melainkan 1 juta yen." },
        { j: "りんごを【一つ】、みかんを【二つ】、バナナを【三つ】ください。", r: "Ringo wo hitotsu, mikan wo futatsu, banana wo mittsu kudasai.", m: "Tolong beri saya satu apel, dua jeruk, dan tiga pisang." },
        { j: "ケーキを【四つ】、パンを【五つ】、あめを【六つ】買いました。", r: "Keeki wo yottsu, pan wo itsutsu, ame wo muttsu kaimashita.", m: "Saya membeli empat kue, lima roti, dan enam permen." },
        { j: "ボールが【七つ】、【八つ】、【九つ】、【十】あります。", r: "Booru ga nanatsu, yattsu, kokonotsu, too arimasu.", m: "Ada bola tujuh, delapan, sembilan, dan sepuluh buah (hitungan satu per satu)." },
        { j: "弟は【六つ】で、妹は【四つ】です。兄は【二十歳】です。", r: "Otouto wa muttsu de, imouto wa yottsu desu. Ani wa hatachi desu.", m: "Adik laki-laki saya berusia 6 tahun, adik perempuan 4 tahun, dan kakak laki-laki saya 20 tahun." }
    ]},
    { id: 2, title: "02 HARI", items: [
        { j: "今日は何【曜日】ですか。 ― 【月曜日】です。", r: "Kyou wa nan youbi desu ka. ― Getsuyoubi desu.", m: "Hari ini hari apa? ― Hari Senin." },
        { j: "【火曜日】と【水曜日】と【木曜日】はアルバイトがあります。", r: "Kayoubi to suiyoubi to mokuyoubi wa arubaito ga arimasu.", m: "Selasa, Rabu, dan Kamis saya ada kerja sambilan." },
        { j: "【金曜日】に友達に会います。【土曜日】と【日曜日】は休みです。", r: "Kin'youbi ni tomodachi ni aimasu. Doyoubi to nichiyoubi wa yasumi desu.", m: "Hari Jumat saya bertemu teman. Sabtu dan Minggu libur." }
    ]},
    { id: 3, title: "03 TGL & HARI", items: [
        { j: "今日は【一日】で、明日は【二日】、あさっては【三日】です。", r: "Kyou wa tsuitachi de, ashita wa futsuka, asatte wa mikka desu.", m: "Hari ini tanggal 1, besok tanggal 2, lusa tanggal 3." },
        { j: "【四日】と【五日】に友達の家へ行きます。", r: "Yokka to itsuka ni tomodachi no ie e ikimasu.", m: "Tanggal 4 dan 5 saya pergi ke rumah teman." },
        { j: "【六日】、【七日】、【八日】は雨でした。", r: "Muika, nanoka, youka wa ame deshita.", m: "Tanggal 6, 7, dan 8 hujan." },
        { j: "【九日】と【十日】はテストがあります。", r: "Kokonoka to tooka wa tesuto ga arimasu.", m: "Tanggal 9 dan 10 ada ujian." },
        { j: "【十一日】から【十四日】まで旅行します。", r: "Juuichinichi kara juuyokka made ryokou shimasu.", m: "Saya berwisata dari tanggal 11 sampai tanggal 14." },
        { j: "【二十日】と【二十四日】は休みです。", r: "Hatsuka to nijuuyokka wa yasumi desu.", m: "Tanggal 20 dan 24 libur." },
        { j: "【一日】に三回、薬を飲みます。", r: "Ichinichi ni sankai, kusuri wo nomimasu.", m: "Dalam sehari saya minum obat tiga kali." },
        { j: "旅行は【二日間】か【三日間】か【四日間】ぐらいです。", r: "Ryokou wa futsukakan ka mikkakan ka yokkakan gurai desu.", m: "Perjalanannya sekitar dua, tiga, atau empat hari." },
        { j: "夏休みは【五日間】で、旅行は【六日間】です。", r: "Natsuyasumi wa itsukakan de, ryokou wa muikakan desu.", m: "Liburan musim panas lima hari, dan perjalanannya enam hari." },
        { j: "かれは日本に【八日間】、私は【九日間】いました。", r: "Kare wa nihon ni youkakan, watashi wa kokonokakan imashita.", m: "Dia berada di Jepang selama 8 hari, saya selama 9 hari." },
        { j: "この本は【七日間】で読みましたが、あの本は【十日間】かかりました。", r: "Kono hon wa nanokakan de yomimashita ga, ano hon wa tookakan kakarimashita.", m: "Buku ini saya baca dalam 7 hari, tetapi buku itu memakan waktu 10 hari." },
        { j: "【一週間】に二回プールへ行きます。【一年間】日本語を勉強して、【一か月間】日本に住みました。", r: "Isshuukan ni nikai puuru e ikimasu. Ichinenkan nihongo wo benkyou shite, ikkagetsukan nihon ni sumimashita.", m: "Seminggu dua kali saya pergi ke kolam renang. Saya belajar bahasa Jepang selama satu tahun dan tinggal di Jepang selama satu bulan." }
    ]},
    { id: 4, title: "04 BULAN", items: [
        { j: "今月は何【月】ですか。 ― 【十月】です。", r: "Kongetsu wa nan gatsu desu ka. ― Juugatsu desu.", m: "Bulan ini bulan apa? ― Bulan Oktober." },
        { j: "【一月】と【二月】は寒いです。", r: "Ichigatsu to nigatsu wa samui desu.", m: "Januari dan Februari dingin." },
        { j: "日本では【三月】、【四月】、【五月】は春です。", r: "Nihon de wa sangatsu, shigatsu, gogatsu wa haru desu.", m: "Di Jepang, Maret, April, dan Mei adalah musim semi." },
        { j: "【六月】、【七月】、【八月】は暑いです。", r: "Rokugatsu, shichigatsu, hachigatsu wa atsui desu.", m: "Juni, Juli, dan Agustus panas." },
        { j: "【九月】、【十月】、【十一月】は秋で、【十二月】は冬です。", r: "Kugatsu, juugatsu, juuichigatsu wa aki de, juunigatsu wa fuyu desu.", m: "September, Oktober, November adalah musim gugur, dan Desember adalah musim dingin." }
    ]},
    { id: 5, title: "05 JAM", items: [
        { j: "【一時】と【二時】の間に昼ご飯を食べます。", r: "Ichi ji to ni ji no aida ni hirugohan wo tabemasu.", m: "Saya makan siang antara jam satu dan jam dua." },
        { j: "【三時】に友達に会って、【四時】に帰って、【五時】に晩ご飯を作ります。", r: "San ji ni tomodachi ni atte, yo ji ni kaette, go ji ni bangohan wo tsukurimasu.", m: "Jam tiga bertemu teman, jam empat pulang, jam lima memasak makan malam." },
        { j: "【十一時】に寝て、【十二時】に電気を消します。", r: "Juuichi ji ni nete, juuni ji ni denki wo keshimasu.", m: "Saya tidur jam sebelas dan mematikan lampu jam dua belas." },
        { j: "学校まで【一時間】かかります。何【時間】ですか。", r: "Gakkou made ichi jikan kakarimasu. Nan jikan desu ka.", m: "Ke sekolah butuh satu jam. Berapa jam?" },
        { j: "うちから店まで【三分】、駅まで【四分】、公園まで【五分】です。", r: "Uchi kara mise made san pun, eki made yon pun, kouen made go fun desu.", m: "Dari rumah ke toko 3 menit, ke stasiun 4 menit, ke taman 5 menit." },
        { j: "家から駅まで【七分】、駅から会社まで【十一分】です。", r: "Ie kara eki made nana fun, eki kara kaisha made juuippun desu.", m: "Dari rumah ke stasiun 7 menit, dari stasiun ke kantor 11 menit." },
        { j: "家から学校まで【九分】、公園まで【二分】、店まで【一分】です。", r: "Ie kara gakkou made kyuu fun, kouen made ni fun, mise made ippun desu.", m: "Dari rumah ke sekolah 9 menit, ke taman 2 menit, ke toko 1 menit." },
        { j: "このバスは【六分】に一本、あのバスは【八分】に一本来ます。", r: "Kono basu wa roppun ni ippon, ano basu wa happun ni ippon kimasu.", m: "Bus ini datang setiap 6 menit, bus itu setiap 8 menit." },
        { j: "【十分】待って、【十五分】休んで、三時【半】に出ます。", r: "Juppun matte, juugofun yasunde, san ji han ni demasu.", m: "Setelah menunggu 10 menit dan istirahat 15 menit, saya berangkat jam setengah empat." }
    ]},
    { id: 6, title: "06 WAKTU", items: [
        { j: "【時間】がありますか。", r: "Jikan ga arimasu ka.", m: "Apakah Anda punya waktu?" },
        { j: "【午前】は学校で、【午後】はアルバイトです。", r: "Gozen wa gakkou de, gogo wa arubaito desu.", m: "Pagi hari saya di sekolah, sore harinya kerja sambilan." },
        { j: "お【先】にどうぞ。私は【今】行きます。", r: "Osaki ni douzo. Watashi wa ima ikimasu.", m: "Silakan duluan. Saya akan pergi sekarang." },
        { j: "【朝】は忙しいです。【今朝】は朝ご飯を食べませんでした。", r: "Asa wa isogashii desu. Kesa wa asagohan wo tabemasen deshita.", m: "Pagi hari sibuk. Tadi pagi saya tidak sarapan." },
        { j: "【昼】は友達と食べて、【夕方】は図書館へ行きます。", r: "Hiru wa tomodachi to tabete, yuugata wa toshokan e ikimasu.", m: "Siang hari saya makan dengan teman, sore hari pergi ke perpustakaan." },
        { j: "【夜】は早く寝ますが、【今夜】は遅くまで勉強します。", r: "Yoru wa hayaku nemasu ga, konya wa osoku made benkyou shimasu.", m: "Malam hari biasanya tidur cepat, tetapi malam ini saya belajar sampai larut." },
        { j: "【今晩】は何を食べますか。", r: "Konban wa nani wo tabemasu ka.", m: "Malam ini mau makan apa?" },
        { j: "【昨夜】はよく寝ました。【夕べ】友達から電話がありました。【昨晩】は雨でした。", r: "Sakuya wa yoku nemashita. Yuube tomodachi kara denwa ga arimashita. Sakuban wa ame deshita.", m: "Tadi malam saya tidur nyenyak. Kemarin malam ada telepon dari teman. Kemarin malam hujan." },
        { j: "【毎朝】六時に起きて、【毎晩】十時に寝ます。【毎日】学校へ行きます。", r: "Maiasa roku ji ni okite, maiban juu ji ni nemasu. Mainichi gakkou e ikimasu.", m: "Setiap pagi saya bangun jam enam, setiap malam tidur jam sepuluh. Setiap hari pergi ke sekolah." },
        { j: "【毎週】日曜日にプールへ行きます。【毎月】友達に会います。【毎年】日本へ行きます。", r: "Maishuu nichiyoubi ni puuru e ikimasu. Maitsuki tomodachi ni aimasu. Maitoshi nihon e ikimasu.", m: "Setiap minggu hari Minggu saya ke kolam renang. Setiap bulan bertemu teman. Setiap tahun pergi ke Jepang." },
        { j: "【一昨日】は雨でしたが、【昨日】は晴れでした。【今日】は曇りです。", r: "Ototoi wa ame deshita ga, kinou wa hare deshita. Kyou wa kumori desu.", m: "Kemarin dulu hujan, kemarin cerah. Hari ini berawan." },
        { j: "【明日】は休みで、【あさって】は仕事です。", r: "Ashita wa yasumi de, asatte wa shigoto desu.", m: "Besok libur, lusa kerja." },
        { j: "【先々週】は忙しかったですが、【先週】は暇でした。", r: "Sensenshuu wa isogashikatta desu ga, senshuu wa hima deshita.", m: "Dua minggu lalu sibuk, minggu lalu senggang." },
        { j: "【今週】は忙しいです。【来週】は休みで、【再来週】は旅行します。", r: "Konshuu wa isogashii desu. Raishuu wa yasumi de, saraishuu wa ryokou shimasu.", m: "Minggu ini sibuk. Minggu depan libur, dan dua minggu lagi saya berwisata." },
        { j: "【先々月】と【先月】は日本にいました。", r: "Sensengetsu to sengetsu wa nihon ni imashita.", m: "Dua bulan lalu dan bulan lalu saya ada di Jepang." },
        { j: "【今月】はアルバイトが多く、【来月】は休みがあります。【再来月】は国へ帰ります。", r: "Kongetsu wa arubaito ga ooku, raigetsu wa yasumi ga arimasu. Saraigetsu wa kuni e kaerimasu.", m: "Bulan ini banyak kerja sambilan, bulan depan ada libur. Dua bulan lagi saya pulang kampung." },
        { j: "【一昨年】日本へ行きました。【去年】は家にいました。【今年】は大学に入ります。", r: "Ototoshi nihon e ikimashita. Kyonen wa ie ni imashita. Kotoshi wa daigaku ni hairimasu.", m: "Dua tahun lalu saya pergi ke Jepang. Tahun lalu di rumah. Tahun ini masuk universitas." },
        { j: "【来年】は日本へ行って、【再来年】は結婚します。", r: "Rainen wa nihon e itte, sarainen wa kekkon shimasu.", m: "Tahun depan saya pergi ke Jepang, dan dua tahun lagi saya menikah." }
    ]},
    { id: 7, title: "07 WARNA", items: [
        { j: "どんな【色】が好きですか。 ― 【青】が好きです。", r: "Donna iro ga suki desu ka. ― Ao ga suki desu.", m: "Warna apa yang kamu suka? ― Saya suka warna biru." },
        { j: "【赤い】りんごと【黄色い】バナナを買いました。", r: "Akai ringo to kiiroi banana wo kaimashita.", m: "Saya membeli apel merah dan pisang kuning." },
        { j: "【黒い】くつと【白い】シャツを着ています。", r: "Kuroi kutsu to shiroi shatsu wo kite imasu.", m: "Saya memakai sepatu hitam dan kemeja putih." },
        { j: "【茶色い】犬と【緑色】の木の写真です。", r: "Chairoi inu to midori iro no ki no shashin desu.", m: "Ini foto anjing coklat dan pohon hijau." },
        { j: "【紫】の花がきれいです。【緑】の山も好きです。", r: "Murasaki no hana ga kirei desu. Midori no yama mo suki desu.", m: "Bunga ungu itu cantik. Saya juga suka gunung yang hijau." }
    ]},
    { id: 8, title: "08 SATUAN", items: [
        { j: "肉を二【キロ】、砂糖を五百【グラム】買いました。", r: "Niku wo ni kiro, satou wo gohyaku guramu kaimashita.", m: "Saya membeli daging 2 kilo dan gula 500 gram." },
        { j: "ここから駅まで三【キロメートル】あります。プールは五十【メートル】です。", r: "Koko kara eki made san kiromeetoru arimasu. Puuru wa gojuu meetoru desu.", m: "Dari sini ke stasiun 3 kilometer. Kolam renangnya 50 meter." },
        { j: "紙を三【枚】ください。この本は百【ページ】あります。", r: "Kami wo san mai kudasai. Kono hon wa hyaku peeji arimasu.", m: "Tolong beri saya tiga lembar kertas. Buku ini ada 100 halaman." },
        { j: "本を二【冊】買いました。", r: "Hon wo ni satsu kaimashita.", m: "Saya membeli dua buku." },
        { j: "一【分】は六十【秒】です。", r: "Ippun wa rokujuu byou desu.", m: "Satu menit adalah enam puluh detik." },
        { j: "私は三【番】の電車に乗ります。一【番目】のドアから入ってください。", r: "Watashi wa san ban no densha ni norimasu. Ichi banme no doa kara haitte kudasai.", m: "Saya naik kereta nomor 3. Silakan masuk dari pintu pertama." },
        { j: "私は【一人】で来ました。友達は【二人】で来ました。家族は四【人】です。", r: "Watashi wa hitori de kimashita. Tomodachi wa futari de kimashita. Kazoku wa yo nin desu.", m: "Saya datang sendirian. Teman saya datang berdua. Keluarga saya empat orang." },
        { j: "えんぴつを三【本】買いました。", r: "Enpitsu wo san bon kaimashita.", m: "Saya membeli tiga batang pensil." },
        { j: "犬が一【匹】、猫が二【匹】います。", r: "Inu ga ippiki, neko ga nihiki imasu.", m: "Ada satu ekor anjing dan dua ekor kucing." },
        { j: "りんごを三【個】食べました。", r: "Ringo wo san ko tabemashita.", m: "Saya makan tiga buah apel." },
        { j: "コーヒーを二【杯】飲みました。", r: "Koohii wo ni hai nomimashita.", m: "Saya minum dua cangkir kopi." }
    ]},
    { id: 9, title: "09 GANTI", items: [
        { j: "【私】は学生です。【あなた】は先生ですか。", r: "Watashi wa gakusei desu. Anata wa sensei desu ka.", m: "Saya mahasiswa. Apakah Anda seorang guru?" },
        { j: "【君】は何を飲む？ ― 【僕】はお茶を飲む。", r: "Kimi wa nani wo nomu? ― Boku wa ocha wo nomu.", m: "Kamu minum apa? ― Saya minum teh. (percakapan akrab)" },
        { j: "【彼】は医者で、【彼女】は先生です。", r: "Kare wa isha de, kanojo wa sensei desu.", m: "Dia (laki-laki) seorang dokter, dia (perempuan) seorang guru." },
        { j: "【私たち】は友達です。【あなたたち】も日本語を勉強しますか。", r: "Watashitachi wa tomodachi desu. Anatatachi mo nihongo wo benkyou shimasu ka.", m: "Kami berteman. Apakah kalian juga belajar bahasa Jepang?" },
        { j: "【彼ら】はサッカーが好きで、【彼女たち】はテニスが好きです。", r: "Karera wa sakkaa ga suki de, kanojotachi wa tenisu ga suki desu.", m: "Mereka (laki-laki) suka sepak bola, mereka (perempuan) suka tenis." },
        { j: "【自分】で料理を作ります。", r: "Jibun de ryouri wo tsukurimasu.", m: "Saya memasak sendiri." }
    ]},
    { id: 10, title: "10 MANUSIA", items: [
        { j: "あの【人】は日本語の先生です。あの【方】は大学の先生です。", r: "Ano hito wa nihongo no sensei desu. Ano kata wa daigaku no sensei desu.", m: "Orang itu guru bahasa Jepang. Beliau itu dosen universitas." },
        { j: "【人間】は水を飲まなければ生きられません。", r: "Ningen wa mizu wo nomanakereba ikiraremasen.", m: "Manusia tidak bisa hidup tanpa minum air." },
        { j: "公園に【大人】と【子供】がいます。【男】の人と【女】の人が話しています。", r: "Kouen ni otona to kodomo ga imasu. Otoko no hito to onna no hito ga hanashite imasu.", m: "Di taman ada orang dewasa dan anak-anak. Seorang pria dan seorang wanita sedang berbicara." },
        { j: "【体】が痛いです。【頭】も痛いです。", r: "Karada ga itai desu. Atama mo itai desu.", m: "Badan saya sakit. Kepala saya juga sakit." },
        { j: "彼女は【髪】が長くて、【目】が大きいです。", r: "Kanojo wa kami ga nagakute, me ga ookii desu.", m: "Dia berambut panjang dan bermata besar." },
        { j: "【鼻】が高くて、【口】が小さいです。", r: "Hana ga takakute, kuchi ga chiisai desu.", m: "Hidungnya mancung dan mulutnya kecil." },
        { j: "【唇】が赤くて、【歯】が白いです。", r: "Kuchibiru ga akakute, ha ga shiroi desu.", m: "Bibirnya merah dan giginya putih." },
        { j: "【耳】で音楽を聞きます。", r: "Mimi de ongaku wo kikimasu.", m: "Saya mendengarkan musik dengan telinga." },
        { j: "【首】と【肩】が痛いです。", r: "Kubi to kata ga itai desu.", m: "Leher dan pundak saya sakit." },
        { j: "【手】に【指】が五本あります。", r: "Te ni yubi ga gohon arimasu.", m: "Di tangan ada lima jari." },
        { j: "兄は【背】が高くて、【胸】が広いです。", r: "Ani wa se ga takakute, mune ga hiroi desu.", m: "Kakak laki-laki saya tinggi dan dadanya bidang." },
        { j: "【おなか】がすきました。【足】も疲れました。", r: "Onaka ga sukimashita. Ashi mo tsukaremashita.", m: "Perut saya lapar. Kaki saya juga capek." }
    ]},
    { id: 11, title: "11 KELUARGA", items: [
        { j: "私の【家族】は五人です。幸せな【家庭】です。", r: "Watashi no kazoku wa gonin desu. Shiawase na katei desu.", m: "Keluarga saya lima orang. Rumah tangga yang bahagia." },
        { j: "【おじいさん】と【おばあさん】は田舎に住んでいます。", r: "Ojiisan to obaasan wa inaka ni sunde imasu.", m: "Kakek dan nenek tinggal di desa." },
        { j: "【祖父】は元気で、【祖母】は料理が上手です。", r: "Sofu wa genki de, sobo wa ryouri ga jouzu desu.", m: "Kakek saya sehat, nenek saya pandai memasak. (kata untuk keluarga sendiri)" },
        { j: "【お父さん】は会社員です。【お母さん】は先生です。", r: "Otousan wa kaishain desu. Okaasan wa sensei desu.", m: "Ayah (Anda/dia) karyawan kantor. Ibu (Anda/dia) seorang guru." },
        { j: "【父】は医者で、【母】は料理が上手です。", r: "Chichi wa isha de, haha wa ryouri ga jouzu desu.", m: "Ayah saya dokter, ibu saya pandai memasak." },
        { j: "【おじさん】は東京に、【おばさん】は大阪に住んでいます。", r: "Ojisan wa toukyou ni, obasan wa oosaka ni sunde imasu.", m: "Paman tinggal di Tokyo, bibi tinggal di Osaka." },
        { j: "【お兄さん】は大学生で、【お姉さん】は会社員です。", r: "Oniisan wa daigakusei de, oneesan wa kaishain desu.", m: "Kakak laki-laki (Anda/dia) mahasiswa, kakak perempuan (Anda/dia) karyawan kantor." },
        { j: "【兄】は背が高いです。【姉】は歌が上手です。", r: "Ani wa se ga takai desu. Ane wa uta ga jouzu desu.", m: "Kakak laki-laki saya tinggi. Kakak perempuan saya pandai bernyanyi." },
        { j: "【弟】は高校生で、【妹】は小学生です。", r: "Otouto wa koukousei de, imouto wa shougakusei desu.", m: "Adik laki-laki saya siswa SMA, adik perempuan saya siswa SD." },
        { j: "【弟さん】と【妹さん】は元気ですか。", r: "Otoutosan to imoutosan wa genki desu ka.", m: "Apakah adik laki-laki dan adik perempuan Anda sehat?" },
        { j: "【両親】は日本にいます。私は三人【兄弟】で、田中さんは二人【姉妹】です。", r: "Ryoushin wa nihon ni imasu. Watashi wa sannin kyoudai de, tanaka san wa futari shimai desu.", m: "Orang tua saya ada di Jepang. Saya tiga bersaudara, dan Tanaka dua bersaudari." }
    ]},
    { id: 12, title: "12 ALAM", items: [
        { j: "今日の【天気】は【晴れ】です。【空】が青いです。", r: "Kyou no tenki wa hare desu. Sora ga aoi desu.", m: "Cuaca hari ini cerah. Langitnya biru." },
        { j: "明日は【曇り】で、【風】が強いです。", r: "Ashita wa kumori de, kaze ga tsuyoi desu.", m: "Besok berawan dan anginnya kencang." },
        { j: "【雨】が降っていて、【雷】も鳴っています。", r: "Ame ga futte ite, kaminari mo natte imasu.", m: "Hujan turun dan petir juga bergemuruh." },
        { j: "北の国では冬に【雪】が降ります。", r: "Kita no kuni de wa fuyu ni yuki ga furimasu.", m: "Di negara bagian utara, salju turun pada musim dingin." },
        { j: "【水】を飲みました。", r: "Mizu wo nomimashita.", m: "Saya minum air." },
        { j: "夏に【海】で泳ぎました。【湖】と【川】もきれいでした。", r: "Natsu ni umi de oyogimashita. Mizuumi to kawa mo kirei deshita.", m: "Pada musim panas saya berenang di laut. Danau dan sungainya juga indah." },
        { j: "【池】に魚がいます。", r: "Ike ni sakana ga imasu.", m: "Di kolam ada ikan." },
        { j: "【山】に【木】がたくさんあります。", r: "Yama ni ki ga takusan arimasu.", m: "Di gunung ada banyak pohon." },
        { j: "【森】の中に【花】が咲いています。", r: "Mori no naka ni hana ga saite imasu.", m: "Bunga-bunga mekar di tengah hutan." }
    ]},
    { id: 13, title: "13 MUSIM", items: [
        { j: "どの【季節】が好きですか。", r: "Dono kisetsu ga suki desu ka.", m: "Kamu suka musim yang mana?" },
        { j: "【春】は暖かくて、【夏】は暑いです。", r: "Haru wa atatakakute, natsu wa atsui desu.", m: "Musim semi hangat dan musim panas panas." },
        { j: "【秋】は涼しくて、【冬】は寒いです。", r: "Aki wa suzushikute, fuyu wa samui desu.", m: "Musim gugur sejuk dan musim dingin dingin." },
        { j: "インドネシアには【雨季】と【乾季】があります。", r: "Indoneshia ni wa uki to kanki ga arimasu.", m: "Di Indonesia ada musim hujan dan musim kemarau." }
    ]},
    { id: 14, title: "14 BINATANG", items: [
        { j: "どんな【動物】が好きですか。", r: "Donna doubutsu ga suki desu ka.", m: "Kamu suka binatang apa?" },
        { j: "私の【ペット】は【犬】で、友達のペットは【猫】です。", r: "Watashi no petto wa inu de, tomodachi no petto wa neko desu.", m: "Binatang peliharaan saya anjing, milik teman saya kucing." },
        { j: "【鳥】が木の上にいます。【にわとり】は卵を産みます。", r: "Tori ga ki no ue ni imasu. Niwatori wa tamago wo umimasu.", m: "Ada burung di atas pohon. Ayam bertelur." },
        { j: "【魚】と【えび】を食べました。", r: "Sakana to ebi wo tabemashita.", m: "Saya makan ikan dan udang." },
        { j: "動物園で【馬】と【象】を見ました。", r: "Doubutsuen de uma to zou wo mimashita.", m: "Di kebun binatang saya melihat kuda dan gajah." }
    ]},
    { id: 15, title: "15 BENDA", items: [
        { j: "かばんの中に【物】がたくさんあります。", r: "Kaban no naka ni mono ga takusan arimasu.", m: "Di dalam tas ada banyak barang." },
        { j: "【帽子】をかぶって、【眼鏡】をかけます。", r: "Boushi wo kabutte, megane wo kakemasu.", m: "Saya memakai topi dan kacamata." },
        { j: "雨なので【傘】を持って行きます。", r: "Ame na node kasa wo motte ikimasu.", m: "Karena hujan, saya membawa payung." },
        { j: "【ハンカチ】と【タオル】を洗いました。", r: "Hankachi to taoru wo araimashita.", m: "Saya mencuci sapu tangan dan handuk." },
        { j: "【石けん】と【シャンプー】で体を洗います。", r: "Sekken to shanpuu de karada wo araimasu.", m: "Saya mencuci badan dengan sabun dan shampo." },
        { j: "【財布】に【お金】が入っています。", r: "Saifu ni okane ga haitte imasu.", m: "Di dompet ada uang." },
        { j: "家では【スリッパ】をはいて、外では【靴下】と【靴】をはきます。", r: "Ie de wa surippa wo haite, soto de wa kutsushita to kutsu wo hakimasu.", m: "Di rumah saya memakai sandal, di luar memakai kaos kaki dan sepatu." },
        { j: "【荷物】が重いです。日本で【お土産】を買いました。", r: "Nimotsu ga omoi desu. Nihon de omiyage wo kaimashita.", m: "Barang bawaan saya berat. Saya membeli oleh-oleh di Jepang." },
        { j: "この【かばん】は軽いです。", r: "Kono kaban wa karui desu.", m: "Tas ini ringan." },
        { j: "父は【たばこ】を吸いません。【マッチ】もありません。", r: "Chichi wa tabako wo suimasen. Macchi mo arimasen.", m: "Ayah saya tidak merokok. Korek api pun tidak ada." },
        { j: "【薬】を飲みました。【鍵】をなくしました。", r: "Kusuri wo nomimashita. Kagi wo nakushimashita.", m: "Saya minum obat. Saya kehilangan kunci." },
        { j: "毎朝【新聞】を読みます。昨日【雑誌】を買いました。", r: "Maiasa shinbun wo yomimasu. Kinou zasshi wo kaimashita.", m: "Setiap pagi saya membaca koran. Kemarin saya membeli majalah." }
    ]},
    { id: 16, title: "16 PAKAIAN", items: [
        { j: "この【洋服】は安いです。", r: "Kono youfuku wa yasui desu.", m: "Pakaian ini murah." },
        { j: "父は【背広】を着て、【ネクタイ】をしめます。", r: "Chichi wa sebiro wo kite, nekutai wo shimemasu.", m: "Ayah saya memakai jas dan mengikat dasi." },
        { j: "【ポケット】の中に鍵があります。", r: "Poketto no naka ni kagi ga arimasu.", m: "Di dalam saku ada kunci." },
        { j: "寒いので【コート】と【セーター】を着ます。", r: "Samui node kooto to seetaa wo kimasu.", m: "Karena dingin, saya memakai mantel dan sweter." },
        { j: "【上着】をぬいで、【ワイシャツ】だけになりました。", r: "Uwagi wo nuide, waishatsu dake ni narimashita.", m: "Saya melepas jaket dan hanya memakai kemeja." },
        { j: "【シャツ】と【スカート】を買いました。", r: "Shatsu to sukaato wo kaimashita.", m: "Saya membeli kaos dan rok." },
        { j: "【ズボン】の【ボタン】がとれました。", r: "Zubon no botan ga toremashita.", m: "Kancing celana panjang saya lepas." }
    ]},
    { id: 17, title: "17 MAKANAN", items: [
        { j: "好きな【食べ物】は何ですか。【飲み物】はお茶です。", r: "Suki na tabemono wa nan desu ka. Nomimono wa ocha desu.", m: "Makanan kesukaanmu apa? Minuman saya teh." },
        { j: "【朝ご飯】は【パン】と【卵】、【昼ご飯】は【お弁当】、【晩ご飯】は【ご飯】と【肉】です。", r: "Asagohan wa pan to tamago, hirugohan wa obentou, bangohan wa gohan to niku desu.", m: "Sarapan roti dan telur, makan siang bekal, makan malam nasi dan daging." },
        { j: "母の【料理】はおいしいです。", r: "Haha no ryouri wa oishii desu.", m: "Masakan ibu saya enak." },
        { j: "【バナナ】と【りんご】と【みかん】が好きです。", r: "Banana to ringo to mikan ga suki desu.", m: "Saya suka pisang, apel, dan jeruk." },
        { j: "【果物】と【野菜】は体にいいです。", r: "Kudamono to yasai wa karada ni ii desu.", m: "Buah dan sayur baik untuk tubuh." },
        { j: "【サラダ】に【トマト】を入れます。パンに【バター】をぬります。", r: "Sarada ni tomato wo iremasu. Pan ni bataa wo nurimasu.", m: "Saya memasukkan tomat ke dalam salad. Saya mengoleskan mentega pada roti." },
        { j: "【牛肉】と【豚肉】と【とり肉】があります。", r: "Gyuuniku to butaniku to toriniku ga arimasu.", m: "Ada daging sapi, daging babi, dan daging ayam." },
        { j: "今日は【チキン】を食べます。", r: "Kyou wa chikin wo tabemasu.", m: "Hari ini saya makan ayam." },
        { j: "毎朝【牛乳】を飲みます。【ミルク】が好きです。", r: "Maiasa gyuunyuu wo nomimasu. Miruku ga suki desu.", m: "Setiap pagi saya minum susu. Saya suka susu." },
        { j: "【お茶】と【紅茶】と【コーヒー】のどれがいいですか。", r: "Ocha to koucha to koohii no dore ga ii desu ka.", m: "Di antara teh hijau, teh, dan kopi, mana yang Anda mau?" },
        { j: "【お酒】は飲みません。", r: "Osake wa nomimasen.", m: "Saya tidak minum minuman keras." },
        { j: "【お菓子】と【飴】を買いました。", r: "Okashi to ame wo kaimashita.", m: "Saya membeli kue dan permen." }
    ]},
    { id: 18, title: "18 HOBI", items: [
        { j: "【音楽】を聞くのが好きです。【歌】も歌います。", r: "Ongaku wo kiku no ga suki desu. Uta mo utaimasu.", m: "Saya suka mendengarkan musik. Saya juga bernyanyi." },
        { j: "兄は【ギター】、姉は【ピアノ】を弾きます。", r: "Ani wa gitaa, ane wa piano wo hikimasu.", m: "Kakak laki-laki saya bermain gitar, kakak perempuan saya bermain piano." },
        { j: "【レコード】で音楽を聞きます。", r: "Rekoodo de ongaku wo kikimasu.", m: "Saya mendengarkan musik dengan piringan hitam." },
        { j: "週末に【映画】を見ます。", r: "Shuumatsu ni eiga wo mimasu.", m: "Saya menonton film pada akhir pekan." },
        { j: "夏休みに【旅行】します。【カメラ】で【写真】をとりました。", r: "Natsuyasumi ni ryokou shimasu. Kamera de shashin wo torimashita.", m: "Saya berwisata saat liburan musim panas. Saya mengambil foto dengan kamera." },
        { j: "【スポーツ】が好きです。日曜日に【パーティー】があります。", r: "Supootsu ga suki desu. Nichiyoubi ni paatii ga arimasu.", m: "Saya suka olahraga. Hari Minggu ada pesta." }
    ]},
    { id: 19, title: "19 KOTA", items: [
        { j: "私の国の【村】は小さいです。この【町】はきれいです。", r: "Watashi no kuni no mura wa chiisai desu. Kono machi wa kirei desu.", m: "Desa di negara saya kecil. Kota ini bersih." },
        { j: "この【道】をまっすぐ行ってください。次の【角】を右に曲がってください。", r: "Kono michi wo massugu itte kudasai. Tsugi no kado wo migi ni magatte kudasai.", m: "Silakan lurus di jalan ini. Belok kanan di tikungan berikutnya." },
        { j: "【交差点】を渡って、【橋】を歩きます。", r: "Kousaten wo watatte, hashi wo arukimasu.", m: "Saya menyeberangi persimpangan dan berjalan di jembatan." },
        { j: "【公園】に【プール】と【テニスコート】があります。", r: "Kouen ni puuru to tenisu kooto ga arimasu.", m: "Di taman ada kolam renang dan lapangan tenis." },
        { j: "【車】（【自動車】）で行きます。", r: "Kuruma (jidousha) de ikimasu.", m: "Saya pergi dengan mobil." },
        { j: "【自転車】で学校へ行きます。【地図】を見て行きます。", r: "Jitensha de gakkou e ikimasu. Chizu wo mite ikimasu.", m: "Saya pergi ke sekolah naik sepeda. Saya berjalan sambil melihat peta." }
    ]},
    { id: 20, title: "20 TRANS", items: [
        { j: "【バイク】（【オートバイ】）で会社へ行きます。", r: "Baiku (ooto baiku) de kaisha e ikimasu.", m: "Saya pergi ke kantor naik motor." },
        { j: "【タクシー】で空港へ行きます。", r: "Takushii de kuukou e ikimasu.", m: "Saya pergi ke bandara naik taksi." },
        { j: "【バス】に乗ります。", r: "Basu ni norimasu.", m: "Saya naik bus." },
        { j: "【船】と【フェリー】で島へ行きました。", r: "Fune to ferii de shima e ikimashita.", m: "Saya pergi ke pulau naik kapal laut dan kapal feri." },
        { j: "【電車】と【地下鉄】で学校へ行きます。", r: "Densha to chikatetsu de gakkou e ikimasu.", m: "Saya pergi ke sekolah naik kereta listrik dan kereta bawah tanah." },
        { j: "【飛行機】で日本へ行きます。【切符】を買ってください。", r: "Hikouki de nihon e ikimasu. Kippu wo katte kudasai.", m: "Saya pergi ke Jepang naik pesawat. Tolong belikan tiket." }
    ]},
    { id: 21, title: "21 SEKOLAH", items: [
        { j: "【学校】は八時に始まります。兄は【大学】に行っています。", r: "Gakkou wa hachi ji ni hajimarimasu. Ani wa daigaku ni itte imasu.", m: "Sekolah mulai jam delapan. Kakak laki-laki saya kuliah di universitas." },
        { j: "【教室】に学生が二十人います。私の【クラス】は二十人です。", r: "Kyoushitsu ni gakusei ga nijuu nin imasu. Watashi no kurasu wa nijuu nin desu.", m: "Di ruang kelas ada dua puluh mahasiswa. Kelas saya terdiri dari dua puluh orang." },
        { j: "【図書館】で本を借ります。", r: "Toshokan de hon wo karimasu.", m: "Saya meminjam buku di perpustakaan." },
        { j: "【授業】は九時からです。日本語の【言葉】を覚えます。", r: "Jugyou wa ku ji kara desu. Nihongo no kotoba wo oboemasu.", m: "Pelajaran mulai jam sembilan. Saya menghafal kata-kata bahasa Jepang." },
        { j: "【英語】と【漢字】は難しいです。", r: "Eigo to kanji wa muzukashii desu.", m: "Bahasa Inggris dan huruf kanji itu sulit." },
        { j: "この【文章】は長いです。【作文】を書きます。", r: "Kono bunshou wa nagai desu. Sakubun wo kakimasu.", m: "Kalimat (tulisan) ini panjang. Saya menulis karangan." },
        { j: "【辞書】（【字引】）で【意味】を調べます。", r: "Jisho (jibiki) de imi wo shirabemasu.", m: "Saya mencari arti kata dengan kamus." },
        { j: "【宿題】がたくさんあります。明日【テスト】（【試験】）があります。", r: "Shukudai ga takusan arimasu. Ashita tesuto (shiken) ga arimasu.", m: "PR-nya banyak. Besok ada tes (ujian)." }
    ]},
    { id: 22, title: "22 BANGUNAN", items: [
        { j: "この【ホテル】は大きいです。友達は【アパート】に住んでいます。", r: "Kono hoteru wa ookii desu. Tomodachi wa apaato ni sunde imasu.", m: "Hotel ini besar. Teman saya tinggal di apartemen." },
        { j: "【デパート】で買い物をします。【駅】で友達を待ちます。", r: "Depaato de kaimono wo shimasu. Eki de tomodachi wo machimasu.", m: "Saya berbelanja di toko serba ada. Saya menunggu teman di stasiun." },
        { j: "【病院】で医者に会います。【美容院】で髪を切ります。", r: "Byouin de isha ni aimasu. Biyouin de kami wo kirimasu.", m: "Saya bertemu dokter di rumah sakit. Saya memotong rambut di salon." },
        { j: "【映画館】で映画を見ます。【銀行】でお金を出します。", r: "Eigakan de eiga wo mimasu. Ginkou de okane wo dashimasu.", m: "Saya menonton film di bioskop. Saya mengambil uang di bank." },
        { j: "【郵便局】で切手を買います。【大使館】はどこですか。", r: "Yuubinkyoku de kitte wo kaimasu. Taishikan wa doko desu ka.", m: "Saya membeli perangko di kantor pos. Di mana kedutaan?" },
        { j: "【交番】で道を聞きます。【会社】は九時からです。", r: "Kouban de michi wo kikimasu. Kaisha wa ku ji kara desu.", m: "Saya bertanya jalan di pos polisi. Kantor mulai jam sembilan." },
        { j: "【レストラン】で食事します。【喫茶店】でコーヒーを飲みます。", r: "Resutoran de shokuji shimasu. Kissaten de koohii wo nomimasu.", m: "Saya makan di restoran. Saya minum kopi di kedai kopi." },
        { j: "この【店】は安いです。【八百屋】で野菜を買います。", r: "Kono mise wa yasui desu. Yaoya de yasai wo kaimasu.", m: "Toko ini murah. Saya membeli sayur di penjual sayur." },
        { j: "あの【建物】は高いです。私の【家】は小さいです。", r: "Ano tatemono wa takai desu. Watashi no ie wa chiisai desu.", m: "Bangunan itu tinggi. Rumah saya kecil." },
        { j: "【エレベーター】と【エスカレーター】で上がります。", r: "Erebeetaa to esukareetaa de agarimasu.", m: "Saya naik dengan lift dan tangga berjalan." },
        { j: "【入口】はここで、【出口】はあそこです。【階段】で下ります。", r: "Iriguchi wa koko de, deguchi wa asoko desu. Kaidan de orimasu.", m: "Pintu masuk di sini, pintu keluar di sana. Saya turun lewat tangga." }
    ]},
    { id: 23, title: "23 RUMAH", items: [
        { j: "【門】の前に車があります。【庭】に花があります。", r: "Mon no mae ni kuruma ga arimasu. Niwa ni hana ga arimasu.", m: "Di depan pintu gerbang ada mobil. Di pekarangan ada bunga." },
        { j: "【玄関】で靴を脱ぎます。", r: "Genkan de kutsu wo nugimasu.", m: "Saya melepas sepatu di pintu depan." },
        { j: "【ドア】（【戸】）を閉めてください。【窓】を開けます。", r: "Doa (to) wo shimete kudasai. Mado wo akemasu.", m: "Tolong tutup pintu. Saya membuka jendela." },
        { j: "【居間】でテレビを見ます。母は【台所】で料理しています。", r: "Ima de terebi wo mimasu. Haha wa daidokoro de ryouri shite imasu.", m: "Saya menonton TV di ruang tamu. Ibu sedang memasak di dapur." },
        { j: "【食堂】で晩ご飯を食べます。【部屋】はきれいです。", r: "Shokudou de bangohan wo tabemasu. Heya wa kirei desu.", m: "Saya makan malam di ruang makan. Kamarnya bersih." },
        { j: "【風呂場】で体を洗います。【シャワー】を浴びます。", r: "Furoba de karada wo araimasu. Shawaa wo abimasu.", m: "Saya mencuci badan di kamar mandi. Saya mandi dengan shower." },
        { j: "【トイレ】（【お手洗い】）はどこですか。", r: "Toire (otearai) wa doko desu ka.", m: "Di mana toiletnya?" },
        { j: "【廊下】は長いです。【電気】をつけてください。", r: "Rouka wa nagai desu. Denki wo tsukete kudasai.", m: "Lorongnya panjang. Tolong nyalakan lampu." },
        { j: "【水道】の水を飲みます。", r: "Suidou no mizu wo nomimasu.", m: "Saya minum air ledeng." }
    ]},
    { id: 24, title: "24 ALAT RT", items: [
        { j: "【ソファ】に座ります。【いす】に座って【机】で勉強します。", r: "Sofa ni suwarimasu. Isu ni suwatte tsukue de benkyou shimasu.", m: "Saya duduk di sofa. Saya duduk di kursi dan belajar di meja." },
        { j: "【テーブル】の上にりんごがあります。【本棚】に本があります。", r: "Teeburu no ue ni ringo ga arimasu. Hondana ni hon ga arimasu.", m: "Di atas meja ada apel. Di rak buku ada buku." },
        { j: "【ベッド】で寝ます。【ふとん】をひきます。", r: "Beddo de nemasu. Futon wo hikimasu.", m: "Saya tidur di ranjang. Saya menggelar futon." },
        { j: "冬は【暖房】（【ストーブ】）を使います。夏は【冷房】を使います。", r: "Fuyu wa danbou (sutoobu) wo tsukaimasu. Natsu wa reibou wo tsukaimasu.", m: "Musim dingin saya memakai pemanas ruangan. Musim panas memakai AC." },
        { j: "この部屋は【冷暖房】があります。", r: "Kono heya wa reidanbou ga arimasu.", m: "Kamar ini punya pengatur suhu panas dan dingin." },
        { j: "【冷蔵庫】に牛乳があります。【テレビ】を見ます。", r: "Reizouko ni gyuunyuu ga arimasu. Terebi wo mimasu.", m: "Di kulkas ada susu. Saya menonton televisi." },
        { j: "【テープレコーダー】で声を録音します。【ラジオ】を聞きます。", r: "Teepu rekoodaa de koe wo rokuon shimasu. Rajio wo kikimasu.", m: "Saya merekam suara dengan tape recorder. Saya mendengarkan radio." },
        { j: "【ラジカセ】で音楽を聞きます。【電話】が鳴りました。", r: "Rajikase de ongaku wo kikimasu. Denwa ga narimashita.", m: "Saya mendengarkan musik dengan radio kaset. Telepon berbunyi." },
        { j: "壁に【絵】と【カレンダー】があります。【時計】は三時です。", r: "Kabe ni e to karendaa ga arimasu. Tokei wa san ji desu.", m: "Di dinding ada lukisan dan kalender. Jam menunjukkan pukul tiga." },
        { j: "【花瓶】に花を入れます。【灰皿】はありません。", r: "Kabin ni hana wo iremasu. Haizara wa arimasen.", m: "Saya menaruh bunga di vas. Tidak ada asbak." }
    ]},
    { id: 25, title: "25 ALAT MAKAN", items: [
        { j: "お【皿】にケーキをのせます。【ナイフ】で肉を切ります。", r: "Osara ni keeki wo nosemasu. Naifu de niku wo kirimasu.", m: "Saya menaruh kue di piring. Saya memotong daging dengan pisau." },
        { j: "【コップ】に水を入れます。", r: "Koppu ni mizu wo iremasu.", m: "Saya menuang air ke dalam gelas." },
        { j: "【スプーン】と【フォーク】でケーキを食べます。", r: "Supuun to fooku de keeki wo tabemasu.", m: "Saya makan kue dengan sendok dan garpu." },
        { j: "日本人は【お箸】を使います。【お茶碗】にご飯を入れます。", r: "Nihonjin wa ohashi wo tsukaimasu. Ochawan ni gohan wo iremasu.", m: "Orang Jepang memakai sumpit. Saya menaruh nasi di mangkok nasi." },
        { j: "【カップ】でコーヒーを飲みます。", r: "Kappu de koohii wo nomimasu.", m: "Saya minum kopi dengan cangkir." }
    ]},
    { id: 26, title: "26 BUMBU", items: [
        { j: "コーヒーに【砂糖】を入れます。", r: "Koohii ni satou wo iremasu.", m: "Saya memasukkan gula ke dalam kopi." },
        { j: "スープに【塩】と【こしょう】を入れます。", r: "Suupu ni shio to koshou wo iremasu.", m: "Saya memasukkan garam dan lada ke dalam sup." },
        { j: "魚に【しょうゆ】をかけます。", r: "Sakana ni shouyu wo kakemasu.", m: "Saya menuangkan kecap asin ke ikan." },
        { j: "【調味料】は台所にあります。", r: "Choumiryou wa daidokoro ni arimasu.", m: "Bumbu dapur ada di dapur." }
    ]},
    { id: 27, title: "27 ALAT TULIS", items: [
        { j: "【紙】に名前を書きます。", r: "Kami ni namae wo kakimasu.", m: "Saya menulis nama di kertas." },
        { j: "【ペン】（【ボールペン】）で書きます。父は【万年筆】を使います。", r: "Pen (booru pen) de kakimasu. Chichi wa mannenhitsu wo tsukaimasu.", m: "Saya menulis dengan pulpen. Ayah saya memakai pena tinta." },
        { j: "【鉛筆】でテストを書きます。", r: "Enpitsu de tesuto wo kakimasu.", m: "Saya mengerjakan tes dengan pensil." },
        { j: "【本】と【ノート】をかばんに入れます。", r: "Hon to nooto wo kaban ni iremasu.", m: "Saya memasukkan buku dan buku tulis ke dalam tas." },
        { j: "友達に【手紙】を書きます。", r: "Tomodachi ni tegami wo kakimasu.", m: "Saya menulis surat untuk teman." },
        { j: "【封筒】に【切手】をはります。【葉書】を出します。", r: "Fuutou ni kitte wo harimasu. Hagaki wo dashimasu.", m: "Saya menempelkan perangko pada amplop. Saya mengirim kartu pos." },
        { j: "【テープ】を【箱】にはります。", r: "Teepu wo hako ni harimasu.", m: "Saya menempelkan selotip pada kotak." }
    ]},
    { id: 28, title: "28 KERJA", items: [
        { j: "父の【仕事】は何ですか。", r: "Chichi no shigoto wa nan desu ka.", m: "Apa pekerjaan ayah Anda?" },
        { j: "【医者】は病院で働きます。", r: "Isha wa byouin de hatarakimasu.", m: "Dokter bekerja di rumah sakit." },
        { j: "【警官】（【おまわりさん】）は交番にいます。", r: "Keikan (omawarisan) wa kouban ni imasu.", m: "Polisi ada di pos polisi." },
        { j: "【先生】は【生徒】に日本語を教えます。", r: "Sensei wa seito ni nihongo wo oshiemasu.", m: "Guru mengajarkan bahasa Jepang kepada murid." },
        { j: "兄は【学生】で、あの人は【留学生】です。", r: "Ani wa gakusei de, ano hito wa ryuugakusei desu.", m: "Kakak saya mahasiswa, dan orang itu pelajar asing." }
    ]},
    { id: 29, title: "29 ARAH", items: [
        { j: "机の【上】に本があります。いすの【下】に猫がいます。", r: "Tsukue no ue ni hon ga arimasu. Isu no shita ni neko ga imasu.", m: "Di atas meja ada buku. Di bawah kursi ada kucing." },
        { j: "家の【前】に木があります。駅の【後ろ】に銀行があります。", r: "Ie no mae ni ki ga arimasu. Eki no ushiro ni ginkou ga arimasu.", m: "Di depan rumah ada pohon. Di belakang stasiun ada bank." },
        { j: "【外】は寒いですが、部屋の【中】は暖かいです。", r: "Soto wa samui desu ga, heya no naka wa atatakai desu.", m: "Di luar dingin, tetapi di dalam kamar hangat." },
        { j: "川の【向こう】に山があります。橋の【手前】に交番があります。", r: "Kawa no mukou ni yama ga arimasu. Hashi no temae ni kouban ga arimasu.", m: "Di seberang sungai ada gunung. Di sebelah sini jembatan ada pos polisi." },
        { j: "【右】と【左】を見てください。", r: "Migi to hidari wo mite kudasai.", m: "Silakan lihat ke kanan dan ke kiri." },
        { j: "私の【隣】は田中さんです。机の【横】に本棚があります。", r: "Watashi no tonari wa tanaka san desu. Tsukue no yoko ni hondana ga arimasu.", m: "Di sebelah saya adalah Tanaka. Di samping meja ada rak buku." },
        { j: "この【辺】に郵便局がありますか。駅の【近く】に住んでいます。", r: "Kono hen ni yuubinkyoku ga arimasu ka. Eki no chikaku ni sunde imasu.", m: "Apakah ada kantor pos di sekitar sini? Saya tinggal di dekat stasiun." },
        { j: "太陽は【東】から出て、【西】に沈みます。", r: "Taiyou wa higashi kara dete, nishi ni shizumimasu.", m: "Matahari terbit dari timur dan terbenam di barat." },
        { j: "【北】は寒く、【南】は暑いです。", r: "Kita wa samuku, minami wa atsui desu.", m: "Utara dingin, selatan panas." }
    ]},
    { id: 30, title: "30 TUNJUK", items: [
        { j: "【これ】は本です。【それ】はノートです。【あれ】は辞書です。", r: "Kore wa hon desu. Sore wa nooto desu. Are wa jisho desu.", m: "Ini buku. Itu buku tulis. Itu (jauh) kamus." },
        { j: "【この】かばんは私のです。【その】かばんは友達の、【あの】かばんは先生のです。", r: "Kono kaban wa watashi no desu. Sono kaban wa tomodachi no, ano kaban wa sensei no desu.", m: "Tas ini milik saya. Tas itu milik teman, tas yang di sana milik guru." },
        { j: "【ここ】は教室です。【そこ】は図書館、【あそこ】は食堂です。", r: "Koko wa kyoushitsu desu. Soko wa toshokan, asoko wa shokudou desu.", m: "Di sini ruang kelas. Di situ perpustakaan, di sana ruang makan." },
        { j: "【こちら】は田中さんです。【そちら】は山田さん、【あちら】は先生です。", r: "Kochira wa tanaka san desu. Sochira wa yamada san, achira wa sensei desu.", m: "Ini Tanaka. Yang di situ Yamada, yang di sana guru. (bentuk hormat)" },
        { j: "【こっち】に来てください。【そっち】は暗いです。【あっち】は明るいです。", r: "Kocchi ni kite kudasai. Socchi wa kurai desu. Acchi wa akarui desu.", m: "Silakan ke arah sini. Di situ gelap. Di sana terang." },
        { j: "【こんな】かばんが欲しいです。【そんな】ことはありません。【あんな】高い車は買えません。", r: "Konna kaban ga hoshii desu. Sonna koto wa arimasen. Anna takai kuruma wa kaemasen.", m: "Saya ingin tas seperti ini. Tidak begitu. Mobil semahal itu tidak bisa saya beli." },
        { j: "【こういう】店が好きです。【そういう】話は聞きたくありません。【ああいう】映画はおもしろいです。", r: "Kouiu mise ga suki desu. Souiu hanashi wa kikitaku arimasen. Aaiu eiga wa omoshiroi desu.", m: "Saya suka toko seperti ini. Saya tidak ingin dengar cerita begitu. Film seperti itu menarik." },
        { j: "【このような】本は初めて見ました。【そのような】服は高いです。【あのような】歌が好きです。", r: "Kono you na hon wa hajimete mimashita. Sono you na fuku wa takai desu. Ano you na uta ga suki desu.", m: "Buku seperti ini baru pertama kali saya lihat. Baju seperti itu mahal. Saya suka lagu seperti itu." },
        { j: "【このように】書いてください。【そのように】しましょう。【あのように】歌いたいです。", r: "Kono you ni kaite kudasai. Sono you ni shimashou. Ano you ni utaitai desu.", m: "Tolong tulis seperti ini. Mari kita lakukan seperti itu. Saya ingin bernyanyi seperti itu." }
    ]},
    { id: 31, title: "31 TANYA", items: [
        { j: "これは【何】ですか。", r: "Kore wa nan desu ka.", m: "Ini apa?" },
        { j: "あの人は【誰】ですか。【どなた】ですか。", r: "Ano hito wa dare desu ka. Donata desu ka.", m: "Siapa orang itu? Siapakah beliau? (bentuk hormat)" },
        { j: "【どうして】遅れましたか。【なぜ】休みましたか。【なんで】泣いていますか。", r: "Doushite okuremashita ka. Naze yasumimashita ka. Nande naite imasu ka.", m: "Mengapa Anda terlambat? Mengapa Anda libur? Mengapa dia menangis?" },
        { j: "トイレは【どこ】ですか。", r: "Toire wa doko desu ka.", m: "Di mana toiletnya?" },
        { j: "【どの】かばんですか。【どれ】がいいですか。", r: "Dono kaban desu ka. Dore ga ii desu ka.", m: "Tas yang mana? Yang mana yang bagus?" },
        { j: "コーヒーと紅茶は【どちら】がいいですか。 ― 【どっち】でもいいです。", r: "Koohii to koucha wa dochira ga ii desu ka. ― Docchi demo ii desu.", m: "Kopi atau teh, mana yang Anda mau? ― Yang mana saja boleh." },
        { j: "【どんな】食べ物が好きですか。【どういう】意味ですか。", r: "Donna tabemono ga suki desu ka. Douiu imi desu ka.", m: "Makanan seperti apa yang kamu suka? Apa artinya?" },
        { j: "【どのような】仕事ですか。【どのように】行きますか。", r: "Dono you na shigoto desu ka. Dono you ni ikimasu ka.", m: "Pekerjaan yang bagaimana? Bagaimana cara pergi ke sana?" },
        { j: "これは【いくら】ですか。りんごは【いくつ】ありますか。", r: "Kore wa ikura desu ka. Ringo wa ikutsu arimasu ka.", m: "Berapa harga ini? Ada berapa buah apel?" },
        { j: "誕生日は【いつ】ですか。", r: "Tanjoubi wa itsu desu ka.", m: "Kapan ulang tahunmu?" },
        { j: "お茶は【いかが】ですか。日本語は【どう】ですか。", r: "Ocha wa ikaga desu ka. Nihongo wa dou desu ka.", m: "Bagaimana kalau minum teh? Bagaimana bahasa Jepang?" }
    ]},
    { id: 32, title: "32 SAMBUNG", items: [
        { j: "朝ご飯を食べました。【そして】、学校へ行きました。", r: "Asagohan wo tabemashita. Soshite, gakkou e ikimashita.", m: "Saya sarapan. Lalu, saya pergi ke sekolah." },
        { j: "行きたいです。【でも】、お金がありません。", r: "Ikitai desu. Demo, okane ga arimasen.", m: "Saya ingin pergi. Tetapi, saya tidak punya uang." },
        { j: "日本語は難しいです。【しかし】、おもしろいです。", r: "Nihongo wa muzukashii desu. Shikashi, omoshiroi desu.", m: "Bahasa Jepang itu sulit. Tetapi, menarik." },
        { j: "パンを食べました。【それから】、コーヒーを飲みました。", r: "Pan wo tabemashita. Sorekara, koohii wo nomimashita.", m: "Saya makan roti. Setelah itu, saya minum kopi." },
        { j: "【では】、始めましょう。【それでは】、また明日。", r: "Dewa, hajimemashou. Soredewa, mata ashita.", m: "Baiklah, mari kita mulai. Kalau begitu, sampai besok." },
        { j: "このカレーは【あまり】辛くないです。", r: "Kono karee wa amari karakunai desu.", m: "Kari ini tidak begitu pedas." },
        { j: "バスは電車【より】遅いです。電車の【ほうが】速いです。", r: "Basu wa densha yori osoi desu. Densha no hou ga hayai desu.", m: "Bus lebih lambat daripada kereta. Kereta lebih cepat." },
        { j: "【また】来てください。", r: "Mata kite kudasai.", m: "Silakan datang lagi." },
        { j: "ご飯【の前に】手を洗います。食事し【た後で】薬を飲みます。", r: "Gohan no mae ni te wo araimasu. Shokuji shita ato de kusuri wo nomimasu.", m: "Sebelum makan saya mencuci tangan. Setelah makan saya minum obat." },
        { j: "友達【と一緒に】映画を見ます。", r: "Tomodachi to issho ni eiga wo mimasu.", m: "Saya menonton film bersama teman." }
    ]},
    { id: 33, title: "33 KET", items: [
        { j: "富士山は日本で【いちばん】高い山です。", r: "Fujisan wa nihon de ichiban takai yama desu.", m: "Gunung Fuji adalah gunung tertinggi di Jepang." },
        { j: "私と妹は【同じ】かばんを持っています。", r: "Watashi to imouto wa onaji kaban wo motte imasu.", m: "Saya dan adik perempuan saya punya tas yang sama." },
        { j: "本が【たくさん】あります。公園に人が【大勢】います。", r: "Hon ga takusan arimasu. Kouen ni hito ga oozei imasu.", m: "Ada banyak buku. Di taman ada banyak orang." },
        { j: "この料理は【結構】おいしいです。今日は【とても】暑いです。", r: "Kono ryouri wa kekkou oishii desu. Kyou wa totemo atsui desu.", m: "Masakan ini cukup enak. Hari ini sangat panas." },
        { j: "砂糖を【少し】入れます。今日はお客が【少ない】です。", r: "Satou wo sukoshi iremasu. Kyou wa okyaku ga sukunai desu.", m: "Saya menambahkan sedikit gula. Hari ini pelanggannya sedikit." },
        { j: "【皆さん】、こんにちは。【皆】元気です。", r: "Minasan, konnichiwa. Minna genki desu.", m: "Selamat siang, semuanya. Semua sehat." },
        { j: "宿題は【全部】終わりました。ケーキを【半分】食べました。", r: "Shukudai wa zenbu owarimashita. Keeki wo hanbun tabemashita.", m: "PR sudah selesai semua. Saya makan setengah kue." },
        { j: "明日は【たぶん】雨です。【だんだん】暖かくなります。", r: "Ashita wa tabun ame desu. Dandan atatakaku narimasu.", m: "Besok mungkin hujan. Lambat laun akan menjadi hangat." },
        { j: "【ちょっと】待ってください。今、【ちょうど】三時です。", r: "Chotto matte kudasai. Ima, choudo san ji desu.", m: "Tolong tunggu sebentar. Sekarang tepat jam tiga." },
        { j: "【次】の駅で降ります。", r: "Tsugi no eki de orimasu.", m: "Saya turun di stasiun berikutnya." },
        { j: "【時々】映画を見ます。【いつも】朝ご飯を食べます。", r: "Tokidoki eiga wo mimasu. Itsumo asagohan wo tabemasu.", m: "Kadang-kadang saya menonton film. Saya selalu sarapan." },
        { j: "【じゃあ】、また明日。【よく】図書館へ行きます。", r: "Jaa, mata ashita. Yoku toshokan e ikimasu.", m: "Kalau begitu, sampai besok. Saya sering pergi ke perpustakaan." },
        { j: "【さあ】、始めましょう。【あ】、雨です！", r: "Saa, hajimemashou. A, ame desu!", m: "Nah, mari kita mulai. Ah, hujan!" },
        { j: "りんごやバナナ【など】を買いました。", r: "Ringo ya banana nado wo kaimashita.", m: "Saya membeli apel, pisang, dan sebagainya." },
        { j: "【始め】から終わりまで読みました。日本へ行くのは【初めて】です。", r: "Hajime kara owari made yomimashita. Nihon e iku no wa hajimete desu.", m: "Saya membaca dari awal sampai akhir. Pergi ke Jepang adalah yang pertama kali bagi saya." },
        { j: "【最後】に名前を書いてください。", r: "Saigo ni namae wo kaite kudasai.", m: "Terakhir, tolong tulis nama Anda." },
        { j: "【大丈夫】ですか。 ― はい、【かまいません】。", r: "Daijoubu desu ka. ― Hai, kamaimasen.", m: "Apakah Anda baik-baik saja? ― Ya, tidak apa-apa." },
        { j: "この紙は【縦】が二十センチ、【横】が十センチです。", r: "Kono kami wa tate ga nijuu senchi, yoko ga juu senchi desu.", m: "Kertas ini panjangnya 20 cm dan lebarnya 10 cm." },
        { j: "【ほか】の本もあります。【本当に】ありがとうございます。", r: "Hoka no hon mo arimasu. Hontou ni arigatou gozaimasu.", m: "Ada buku yang lain juga. Terima kasih banyak." },
        { j: "【まだ】食べていません。【もう】食べました。", r: "Mada tabete imasen. Mou tabemashita.", m: "Saya belum makan. Saya sudah makan." },
        { j: "【もっと】ください。【ゆっくり】話してください。", r: "Motto kudasai. Yukkuri hanashite kudasai.", m: "Tolong beri lebih banyak. Tolong bicara perlahan-lahan." },
        { j: "【早く】起きて、【速く】走ります。", r: "Hayaku okite, hayaku hashirimasu.", m: "Saya bangun pagi-pagi dan berlari cepat." }
    ]},
    { id: 34, title: "34 SIFAT -I", items: [
        { j: "この部屋は【明るい】ですが、【狭い】です。", r: "Kono heya wa akarui desu ga, semai desu.", m: "Kamar ini terang, tetapi sempit." },
        { j: "春は【暖かい】ですが、夏は【暑い】です。", r: "Haru wa atatakai desu ga, natsu wa atsui desu.", m: "Musim semi hangat, tetapi musim panas panas." },
        { j: "このお茶は【熱い】ですが、あの水は【冷たい】です。", r: "Kono ocha wa atsui desu ga, ano mizu wa tsumetai desu.", m: "Teh ini panas, tetapi air itu dingin." },
        { j: "この家は【古い】ですが、あの家は【新しい】です。", r: "Kono ie wa furui desu ga, ano ie wa atarashii desu.", m: "Rumah ini tua, tetapi rumah itu baru." },
        { j: "新幹線は【速い】ですが、バスは【遅い】です。", r: "Shinkansen wa hayai desu ga, basu wa osoi desu.", m: "Shinkansen cepat, tetapi bus lambat." },
        { j: "【忙しい】ので、【欲しい】かばんを買いに行けません。", r: "Isogashii node, hoshii kaban wo kai ni ikemasen.", m: "Karena sibuk, saya tidak bisa pergi membeli tas yang saya inginkan." },
        { j: "このかばんは【軽い】ですが、あのかばんは【重い】です。", r: "Kono kaban wa karui desu ga, ano kaban wa omoi desu.", m: "Tas ini ringan, tetapi tas itu berat." },
        { j: "空は【青い】です。りんごは【赤い】です。バナナは【黄色い】です。", r: "Sora wa aoi desu. Ringo wa akai desu. Banana wa kiiroi desu.", m: "Langit biru. Apel merah. Pisang kuning." },
        { j: "このケーキは【甘い】ですが、このカレーは【辛い】です。", r: "Kono keeki wa amai desu ga, kono karee wa karai desu.", m: "Kue ini manis, tetapi kari ini pedas." },
        { j: "この辞書は【厚い】ですが、あのノートは【薄い】です。", r: "Kono jisho wa atsui desu ga, ano nooto wa usui desu.", m: "Kamus ini tebal, tetapi buku tulis itu tipis." },
        { j: "犬は【小さい】ですが、馬は【大きい】です。", r: "Inu wa chiisai desu ga, uma wa ookii desu.", m: "Anjing kecil, tetapi kuda besar." },
        { j: "駅は【近い】ですが、学校は【遠い】です。", r: "Eki wa chikai desu ga, gakkou wa tooi desu.", m: "Stasiun dekat, tetapi sekolah jauh." },
        { j: "あの木は【太い】ですが、あの人は【細い】です。", r: "Ano ki wa futoi desu ga, ano hito wa hosoi desu.", m: "Pohon itu besar (gemuk), tetapi orang itu kurus." },
        { j: "【早い】ですね。もう宿題が終わりましたか。", r: "Hayai desu ne. Mou shukudai ga owarimashita ka.", m: "Cepat sekali ya. Apakah PR-nya sudah selesai?" },
        { j: "あの山は【低い】ですが、この山は【高い】です。", r: "Ano yama wa hikui desu ga, kono yama wa takai desu.", m: "Gunung itu rendah, tetapi gunung ini tinggi." },
        { j: "この公園は【広い】です。", r: "Kono kouen wa hiroi desu.", m: "Taman ini luas." },
        { j: "【いい】天気ですね。【よい】一日を！", r: "Ii tenki desu ne. Yoi ichinichi wo!", m: "Cuacanya bagus ya. Semoga harimu menyenangkan!" },
        { j: "頭が【痛い】です。", r: "Atama ga itai desu.", m: "Kepala saya sakit." },
        { j: "あの子は【かわいい】です。", r: "Ano ko wa kawaii desu.", m: "Anak itu lucu." },
        { j: "ここは【危ない】ですから、気をつけてください。", r: "Koko wa abunai desu kara, ki wo tsukete kudasai.", m: "Di sini berbahaya, jadi harap hati-hati." },
        { j: "手が【汚い】ので、洗います。部屋が【暗い】ので、電気をつけます。", r: "Te ga kitanai node, araimasu. Heya ga kurai node, denki wo tsukemasu.", m: "Karena tangan kotor, saya mencucinya. Karena kamar gelap, saya menyalakan lampu." },
        { j: "【黒い】くつは【白い】シャツに合います。", r: "Kuroi kutsu wa shiroi shatsu ni aimasu.", m: "Sepatu hitam cocok dengan kemeja putih." },
        { j: "【丸い】テーブルが欲しいです。", r: "Marui teeburu ga hoshii desu.", m: "Saya ingin meja bundar." },
        { j: "このスープは【まずい】ですが、あのスープは【おいしい】です。", r: "Kono suupu wa mazui desu ga, ano suupu wa oishii desu.", m: "Sup ini tidak enak, tetapi sup itu enak." },
        { j: "髪は【短い】ですが、川は【長い】です。", r: "Kami wa mijikai desu ga, kawa wa nagai desu.", m: "Rambut (saya) pendek, tetapi sungai itu panjang." },
        { j: "日本語は【難しい】ですが、【おもしろい】です。このテストは【易しい】です。", r: "Nihongo wa muzukashii desu ga, omoshiroi desu. Kono tesuto wa yasashii desu.", m: "Bahasa Jepang sulit, tetapi menarik. Tes ini mudah." },
        { j: "このコーヒーは【温い】です。", r: "Kono koohii wa nurui desu.", m: "Kopi ini suam-suam kuku (tidak cukup panas)." },
        { j: "この町は人が【多い】ですが、あの村は人が【少ない】です。", r: "Kono machi wa hito ga ooi desu ga, ano mura wa hito ga sukunai desu.", m: "Kota ini banyak orangnya, tetapi desa itu sedikit orangnya." },
        { j: "このスープは【しょっぱい】です。", r: "Kono suupu wa shoppai desu.", m: "Sup ini asin." },
        { j: "冬は【寒い】ですが、秋は【涼しい】です。", r: "Fuyu wa samui desu ga, aki wa suzushii desu.", m: "Musim dingin dingin, tetapi musim gugur sejuk." },
        { j: "パーティーは【楽しい】ですが、この映画は【つまらない】です。", r: "Paatii wa tanoshii desu ga, kono eiga wa tsumaranai desu.", m: "Pesta itu menyenangkan, tetapi film ini membosankan." },
        { j: "彼は【強い】ですが、あの子は【弱い】です。", r: "Kare wa tsuyoi desu ga, ano ko wa yowai desu.", m: "Dia kuat, tetapi anak itu lemah." },
        { j: "隣の部屋が【うるさい】です。天気が【悪い】です。", r: "Tonari no heya ga urusai desu. Tenki ga warui desu.", m: "Kamar sebelah berisik. Cuacanya buruk." },
        { j: "この店は【安い】ですが、あの店は【高い】です。", r: "Kono mise wa yasui desu ga, ano mise wa takai desu.", m: "Toko ini murah, tetapi toko itu mahal." },
        { j: "妹は【若い】です。", r: "Imouto wa wakai desu.", m: "Adik perempuan saya masih muda." }
    ]},
    { id: 35, title: "35 NON-I", items: [
        { j: "野菜は【嫌い】です。雨の日は【嫌】です。", r: "Yasai wa kirai desu. Ame no hi wa iya desu.", m: "Saya benci sayuran. Saya tidak suka hari hujan." },
        { j: "この町は【安全】です。電車は【便利】です。", r: "Kono machi wa anzen desu. Densha wa benri desu.", m: "Kota ini aman. Kereta itu praktis." },
        { j: "祖父は【元気】です。今日は【暇】です。", r: "Sofu wa genki desu. Kyou wa hima desu.", m: "Kakek saya sehat. Hari ini saya senggang." },
        { j: "私は料理が【下手】です。姉は【上手】です。", r: "Watashi wa ryouri ga heta desu. Ane wa jouzu desu.", m: "Saya tidak pandai memasak. Kakak perempuan saya pandai." },
        { j: "店に【色々】な物があります。", r: "Mise ni iroiro na mono ga arimasu.", m: "Di toko ada bermacam-macam barang." },
        { j: "このかばんは【丈夫】です。", r: "Kono kaban wa joubu desu.", m: "Tas ini kuat dan tahan lama." },
        { j: "この町は【きれい】です。市場は【にぎやか】です。", r: "Kono machi wa kirei desu. Ichiba wa nigiyaka desu.", m: "Kota ini bersih. Pasar itu ramai." },
        { j: "【りっぱ】な家ですね。先生は【親切】です。", r: "Rippa na ie desu ne. Sensei wa shinsetsu desu.", m: "Rumah yang megah ya. Guru itu ramah." },
        { j: "私は音楽が【好き】で、歌が【大好き】です。", r: "Watashi wa ongaku ga suki de, uta ga daisuki desu.", m: "Saya suka musik dan sangat suka lagu." },
        { j: "図書館は【静か】です。仕事が【大変】です。", r: "Toshokan wa shizuka desu. Shigoto ga taihen desu.", m: "Perpustakaan itu tenang. Pekerjaannya menyusahkan." },
        { j: "このテストは【簡単】です。", r: "Kono tesuto wa kantan desu.", m: "Tes ini mudah." },
        { j: "家族は【大切】です。あの先生は【有名】です。", r: "Kazoku wa taisetsu desu. Ano sensei wa yuumei desu.", m: "Keluarga itu penting. Guru itu terkenal." }
    ]},
    { id: 36, title: "36 GOL I", items: [
        { j: "この店は九時に【開き】ます。おなかが【空き】ました。", r: "Kono mise wa ku ji ni akimasu. Onaka ga sukimashita.", m: "Toko ini buka jam sembilan. Perut saya lapar (kosong)." },
        { j: "ズボンと靴を【はき】ます。", r: "Zubon to kutsu wo hakimasu.", m: "Saya memakai celana panjang dan sepatu." },
        { j: "兄はギターを【弾き】ます。", r: "Ani wa gitaa wo hikimasu.", m: "Kakak laki-laki saya bermain gitar." },
        { j: "先生の話を【聞き】ます。赤ちゃんが【泣き】ます。", r: "Sensei no hanashi wo kikimasu. Akachan ga nakimasu.", m: "Saya mendengarkan cerita guru. Bayi menangis." },
        { j: "時間がないので【急ぎ】ます。", r: "Jikan ga nai node isogimasu.", m: "Karena tidak ada waktu, saya terburu-buru." },
        { j: "子供は公園で【遊び】ます。学生は教室の前に【並び】ます。", r: "Kodomo wa kouen de asobimasu. Gakusei wa kyoushitsu no mae ni narabimasu.", m: "Anak-anak bermain di taman. Mahasiswa berbaris di depan kelas." },
        { j: "毎朝公園を【歩き】ます。母は会社で【働き】ます。", r: "Maiasa kouen wo arukimasu. Haha wa kaisha de hatarakimasu.", m: "Setiap pagi saya berjalan kaki di taman. Ibu saya bekerja di kantor." },
        { j: "毎日学校へ【行き】ます。洗濯物が【乾き】ます。", r: "Mainichi gakkou e ikimasu. Sentakumono ga kawakimasu.", m: "Setiap hari saya pergi ke sekolah. Cucian menjadi kering." },
        { j: "机の上に本を【置き】ます。荷物が【届き】ます。", r: "Tsukue no ue ni hon wo okimasu. Nimotsu ga todokimasu.", m: "Saya meletakkan buku di atas meja. Barang bawaan tiba." },
        { j: "家に入る前に靴を【脱ぎ】ます。重い荷物を【運び】ます。", r: "Ie ni hairu mae ni kutsu wo nugimasu. Omoi nimotsu wo hakobimasu.", m: "Sebelum masuk rumah saya melepas sepatu. Saya mengangkut barang berat." },
        { j: "鳥が空を【飛び】ます。かぜを【引き】ました。", r: "Tori ga sora wo tobimasu. Kaze wo hikimashita.", m: "Burung terbang di langit. Saya terserang flu." },
        { j: "手紙を【書き】ます。歯を【磨き】ます。", r: "Tegami wo kakimasu. Ha wo migakimasu.", m: "Saya menulis surat. Saya menggosok gigi." },
        { j: "春に花が【咲き】ます。八時に学校に【着き】ます。", r: "Haru ni hana ga sakimasu. Hachi ji ni gakkou ni tsukimasu.", m: "Bunga mekar di musim semi. Saya tiba di sekolah jam delapan." },
        { j: "海で【泳ぎ】ます。大学で日本語を【学び】ます。", r: "Umi de oyogimasu. Daigaku de nihongo wo manabimasu.", m: "Saya berenang di laut. Saya belajar bahasa Jepang di universitas." },
        { j: "友達を【呼び】ます。風が【吹き】ます。", r: "Tomodachi wo yobimasu. Kaze ga fukimasu.", m: "Saya memanggil teman. Angin bertiup." },
        { j: "水を【飲み】ます。東京に【住み】ます。", r: "Mizu wo nomimasu. Toukyou ni sumimasu.", m: "Saya minum air. Saya tinggal di Tokyo." },
        { j: "友達に手伝いを【頼み】ます。日曜日は【休み】ます。", r: "Tomodachi ni tetsudai wo tanomimasu. Nichiyoubi wa yasumimasu.", m: "Saya meminta bantuan teman. Hari Minggu saya beristirahat." },
        { j: "本を【読み】ます。魚が【死に】ました。", r: "Hon wo yomimasu. Sakana ga shinimashita.", m: "Saya membaca buku. Ikan itu mati." },
        { j: "友達に【会い】ます。手を【洗い】ます。", r: "Tomodachi ni aimasu. Te wo araimasu.", m: "Saya bertemu teman. Saya mencuci tangan." },
        { j: "これは私の本と【違い】ます。お金を【払い】ます。", r: "Kore wa watashi no hon to chigaimasu. Okane wo haraimasu.", m: "Ini berbeda dengan buku saya. Saya membayar uang." },
        { j: "先生が「いい」と【言い】ます。かばんを【買い】ます。", r: "Sensei ga \"ii\" to iimasu. Kaban wo kaimasu.", m: "Guru berkata \"bagus\". Saya membeli tas." },
        { j: "友達からお土産を【もらい】ます。日本語を【習い】ます。", r: "Tomodachi kara omiyage wo moraimasu. Nihongo wo naraimasu.", m: "Saya menerima oleh-oleh dari teman. Saya belajar bahasa Jepang." },
        { j: "父はたばこを【吸い】ません。母の料理を【手伝い】ます。", r: "Chichi wa tabako wo suimasen. Haha no ryouri wo tetsudaimasu.", m: "Ayah saya tidak merokok. Saya membantu masakan ibu." },
        { j: "ペンを【使い】ます。カラオケで【歌い】ます。友達は【笑い】ます。", r: "Pen wo tsukaimasu. Karaoke de utaimasu. Tomodachi wa waraimasu.", m: "Saya memakai pulpen. Saya bernyanyi di karaoke. Teman saya tertawa." },
        { j: "駅で友達を【待ち】ます。かばんを【持ち】ます。", r: "Eki de tomodachi wo machimasu. Kaban wo mochimasu.", m: "Saya menunggu teman di stasiun. Saya membawa tas." },
        { j: "いすから【立ち】ます。二階に【上がり】ます。", r: "Isu kara tachimasu. Nikai ni agarimasu.", m: "Saya berdiri dari kursi. Saya naik ke lantai dua." },
        { j: "机の上に本が【あり】ます。雨が【降り】ます。", r: "Tsukue no ue ni hon ga arimasu. Ame ga furimasu.", m: "Di atas meja ada buku. Hujan turun." },
        { j: "テストまで【頑張り】ます。部屋に【入り】ます。", r: "Tesuto made ganbarimasu. Heya ni hairimasu.", m: "Saya berusaha sampai ujian. Saya masuk ke kamar." },
        { j: "授業が【始まり】ます。切手を【貼り】ます。公園を【走り】ます。", r: "Jugyou ga hajimarimasu. Kitte wo harimasu. Kouen wo hashirimasu.", m: "Pelajaran dimulai. Saya menempel perangko. Saya berlari di taman." },
        { j: "お金が【要り】ます。帽子を【被り】ます。家へ【帰り】ます。", r: "Okane ga irimasu. Boushi wo kaburimasu. Ie e kaerimasu.", m: "Saya butuh uang. Saya memakai topi. Saya pulang ke rumah." },
        { j: "駅まで十分【かかり】ます。肉を【切り】ます。", r: "Eki made juppun kakarimasu. Niku wo kirimasu.", m: "Ke stasiun memerlukan sepuluh menit. Saya memotong daging." },
        { j: "宿題がなくて【困り】ます。空が【曇り】ます。", r: "Shukudai ga nakute komarimasu. Sora ga kumorimasu.", m: "Saya kesusahan karena tidak ada PR. Langit menjadi mendung." },
        { j: "次の角を【曲がり】ます。席に【戻り】ます。", r: "Tsugi no kado wo magarimasu. Seki ni modorimasu.", m: "Saya berbelok di tikungan berikutnya. Saya kembali ke tempat duduk." },
        { j: "医者に【なり】ます。山に【登り】ます。電車に【乗り】ます。", r: "Isha ni narimasu. Yama ni noborimasu. Densha ni norimasu.", m: "Saya akan menjadi dokter. Saya mendaki gunung. Saya naik kereta." },
        { j: "パーティーで【踊り】ます。手紙を【送り】ます。授業が【終わり】ます。", r: "Paatii de odorimasu. Tegami wo okurimasu. Jugyou ga owarimasu.", m: "Saya menari di pesta. Saya mengirim surat. Pelajaran selesai." },
        { j: "気温が【下がり】ます。店が【閉まり】ます。彼を【知り】ます。", r: "Kion ga sagarimasu. Mise ga shimarimasu. Kare wo shirimasu.", m: "Suhu turun. Toko tutup. Saya mengenal dia." },
        { j: "いすに【座り】ます。バスが【止まり】ます。", r: "Isu ni suwarimasu. Basu ga tomarimasu.", m: "Saya duduk di kursi. Bus berhenti." },
        { j: "塩を【取り】ます。写真を【撮り】ます。", r: "Shio wo torimasu. Shashin wo torimasu.", m: "Saya mengambil garam. Saya mengambil foto." },
        { j: "料理を【作り】ます。この店は野菜を【売り】ます。", r: "Ryouri wo tsukurimasu. Kono mise wa yasai wo urimasu.", m: "Saya membuat masakan. Toko ini menjual sayuran." },
        { j: "日本語が【分かり】ます。川を【渡り】ます。", r: "Nihongo ga wakarimasu. Kawa wo watarimasu.", m: "Saya mengerti bahasa Jepang. Saya menyeberangi sungai." },
        { j: "かばんからノートを【出し】ます。友達にペンを【貸し】ます。", r: "Kaban kara nooto wo dashimasu. Tomodachi ni pen wo kashimasu.", m: "Saya mengeluarkan buku dari tas. Saya meminjamkan pulpen ke teman." },
        { j: "宿題を【やり】ます。先生と【話し】ます。", r: "Shukudai wo yarimasu. Sensei to hanashimasu.", m: "Saya mengerjakan PR. Saya berbicara dengan guru." },
        { j: "本を【返し】ます。電気を【消し】ます。財布を【無くし】ます。", r: "Hon wo kaeshimasu. Denki wo keshimasu. Saifu wo nakushimasu.", m: "Saya mengembalikan buku. Saya mematikan lampu. Saya menghilangkan dompet." },
        { j: "傘を【さし】ます。鍵を【探し】ます。", r: "Kasa wo sashimasu. Kagi wo sagashimasu.", m: "Saya memakai payung. Saya mencari kunci." },
        { j: "切符を【渡し】ます。ボタンを【押し】ます。", r: "Kippu wo watashimasu. Botan wo oshimasu.", m: "Saya menyerahkan tiket. Saya menekan tombol." }
    ]},
    { id: 37, title: "37 GOL II", items: [
        { j: "テレビを【見】ます。シャツを【着】ます。", r: "Terebi wo mimasu. Shatsu wo kimasu.", m: "Saya menonton televisi. Saya mengenakan kemeja." },
        { j: "六時に【起き】ます。バスから【降り】ます。", r: "Roku ji ni okimasu. Basu kara orimasu.", m: "Saya bangun jam enam. Saya turun dari bus." },
        { j: "図書館で本を【借り】ます。シャワーを【あび】ます。", r: "Toshokan de hon wo karimasu. Shawaa wo abimasu.", m: "Saya meminjam buku di perpustakaan. Saya mandi dengan shower." },
        { j: "日本語が【でき】ます。家に猫が【い】ます。", r: "Nihongo ga dekimasu. Ie ni neko ga imasu.", m: "Saya bisa bahasa Jepang. Di rumah ada kucing." }
    ]},
    { id: 38, title: "38 GOL III", items: [
        { j: "友達にお土産を【あげ】ます。友達が私にペンを【くれ】ます。", r: "Tomodachi ni omiyage wo agemasu. Tomodachi ga watashi ni pen wo kuremasu.", m: "Saya memberi oleh-oleh kepada teman. Teman memberi saya pulpen." },
        { j: "八時に家を【出】ます。毎朝【出かけ】ます。", r: "Hachi ji ni ie wo demasu. Maiasa dekakemasu.", m: "Saya keluar rumah jam delapan. Setiap pagi saya keluar rumah." },
        { j: "眼鏡を【かけ】ます。十一時に【寝】ます。", r: "Megane wo kakemasu. Juuichi ji ni nemasu.", m: "Saya memakai kacamata. Saya tidur jam sebelas." },
        { j: "ネクタイを【締め】ます。今日はとても【疲れ】ました。", r: "Nekutai wo shimemasu. Kyou wa totemo tsukaremashita.", m: "Saya mengikat dasi. Hari ini saya sangat letih." },
        { j: "私は東京で【生まれ】ました。天気が【晴れ】ます。", r: "Watashi wa toukyou de umaremashita. Tenki ga haremasu.", m: "Saya lahir di Tokyo. Cuaca menjadi cerah." },
        { j: "窓を【開け】ます。電気が【消え】ます。ドアを【閉め】ます。", r: "Mado wo akemasu. Denki ga kiemasu. Doa wo shimemasu.", m: "Saya membuka jendela. Lampu padam. Saya menutup pintu." },
        { j: "写真を【見せ】ます。言葉を【覚え】ます。", r: "Shashin wo misemasu. Kotoba wo oboemasu.", m: "Saya memperlihatkan foto. Saya menghafal kata-kata." },
        { j: "エアコンを【つけ】ます。かばんに本を【入れ】ます。", r: "Eakon wo tsukemasu. Kaban ni hon wo iremasu.", m: "Saya menyalakan AC. Saya memasukkan buku ke dalam tas." },
        { j: "質問に【答え】ます。テーブルにお皿を【並べ】ます。", r: "Shitsumon ni kotaemasu. Teeburu ni osara wo narabemasu.", m: "Saya menjawab pertanyaan. Saya menyusun piring di meja." },
        { j: "先生は日本語を【教え】ます。毎日ご飯を【食べ】ます。", r: "Sensei wa nihongo wo oshiemasu. Mainichi gohan wo tabemasu.", m: "Guru mengajar bahasa Jepang. Setiap hari saya makan nasi." },
        { j: "父は銀行に【勤め】ます。宿題を【忘れ】ました。", r: "Chichi wa ginkou ni tsutomemasu. Shukudai wo wasuremashita.", m: "Ayah saya bekerja di bank. Saya lupa PR." }
    ]},
    { id: 39, title: "39 GOL IV", items: [
        { j: "友達が私の家に【来】ます。", r: "Tomodachi ga watashi no ie ni kimasu.", m: "Teman saya datang ke rumah saya." },
        { j: "明日、先生が【来】ます。", r: "Ashita, sensei ga kimasu.", m: "Besok guru akan datang." }
    ]},
    { id: 40, title: "40 GOL V", items: [
        { j: "毎日宿題を【し】ます。", r: "Mainichi shukudai wo shimasu.", m: "Setiap hari saya mengerjakan PR." },
        { j: "毎晩日本語を【勉強し】ます。", r: "Maiban nihongo wo benkyou shimasu.", m: "Setiap malam saya belajar bahasa Jepang." },
        { j: "来年【結婚し】ます。", r: "Rainen kekkon shimasu.", m: "Tahun depan saya akan menikah." },
        { j: "友達は【入院し】ます。来週【退院し】ます。", r: "Tomodachi wa nyuuin shimasu. Raishuu tai'in shimasu.", m: "Teman saya masuk rumah sakit. Minggu depan ia keluar dari rumah sakit." },
        { j: "毎日ピアノを【練習し】ます。", r: "Mainichi piano wo renshuu shimasu.", m: "Setiap hari saya berlatih piano." },
        { j: "夏休みに【旅行し】ます。毎朝【散歩し】ます。", r: "Natsuyasumi ni ryokou shimasu. Maiasa sanpo shimasu.", m: "Saat liburan musim panas saya berwisata. Setiap pagi saya berjalan-jalan." },
        { j: "母は毎日【料理し】ます。父は車を【運転し】ます。", r: "Haha wa mainichi ryouri shimasu. Chichi wa kuruma wo unten shimasu.", m: "Ibu saya memasak setiap hari. Ayah saya menyetir mobil." },
        { j: "来年日本へ【留学し】ます。", r: "Rainen nihon e ryuugaku shimasu.", m: "Tahun depan saya belajar ke luar negeri di Jepang." },
        { j: "日曜日に【洗濯し】ます。毎日【掃除し】ます。", r: "Nichiyoubi ni sentaku shimasu. Mainichi souji shimasu.", m: "Hari Minggu saya mencuci pakaian. Setiap hari saya membersihkan rumah." },
        { j: "父は会社で【仕事し】ます。毎朝【運動し】ます。", r: "Chichi wa kaisha de shigoto shimasu. Maiasa undou shimasu.", m: "Ayah saya bekerja di kantor. Setiap pagi saya berolahraga." },
        { j: "友達を【紹介し】ます。三月に大学を【卒業し】ます。", r: "Tomodachi wo shoukai shimasu. Sangatsu ni daigaku wo sotsugyou shimasu.", m: "Saya memperkenalkan teman. Bulan Maret saya lulus dari universitas." },
        { j: "この紙を【コピーし】ます。", r: "Kono kami wo kopii shimasu.", m: "Saya mengkopi kertas ini." }
    ]}
];
